import SalonHeader from "../components/SalonHeader";

export const metadata = { title: "Nehtové studio Plzeň | Bílé nároží", description: "Gelová modeláž nehtů v salonu Bílé nároží v centru Plzně." };

const services = [
  ["Gelová modeláž nehtů", "Precizní modeláž s důrazem na přirozený vzhled a pohodlné nošení."],
  ["Zpevnění přírodních nehtů", "Péče pro upravené a pevnější přírodní nehty."],
  ["Doplnění modeláže", "Pravidelná údržba pro dlouhodobě krásný výsledek."],
  ["Barevné a jemné zdobení", "Styl od čisté elegance po výraznější sezónní vzhled."],
  ["Domácí péče", "Pilníky, lepidla a vybraný sortiment pro běžnou domácí úpravu."],
];

export default function Nehty(){return <main className="lux-page theme-nails"><SalonHeader active="Nehtové studio" />
<section className="lux-hero"><div className="lux-hero-copy"><p className="lux-kicker">Nehtové studio · Plzeň</p><h1>Detail, který<br/><em>dělá rozdíl.</em></h1><p>Gelová modeláž a profesionální péče o ruce s důrazem na preciznost, přirozený vzhled a kvalitní materiály.</p><div className="lux-actions"><a className="lux-btn primary" href="#objednani">Objednat se</a><a className="lux-btn secondary" href="tel:+420724247446">Zavolat do studia</a></div></div><div className="lux-visual" aria-hidden="true" style={{backgroundImage:"linear-gradient(120deg, rgba(44,28,22,.05), rgba(44,28,22,.22)), url('https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=1600&q=88')",backgroundSize:"cover",backgroundPosition:"center"}}><div className="visual-frame" style={{background:"linear-gradient(160deg,rgba(255,255,255,.18),rgba(255,255,255,.02))",backdropFilter:"blur(2px)"}}><span>NAILS</span><strong>DETAIL<br/>MATTERS</strong></div></div></section>
<section className="benefit-strip"><div><span>01</span><strong>Precizní práce</strong><small>Důraz na čistý a upravený výsledek.</small></div><div><span>02</span><strong>Kvalitní materiály</strong><small>Profesionální gely prověřených značek.</small></div><div><span>03</span><strong>Osobní styl</strong><small>Tvar a vzhled podle vašeho přání.</small></div><div><span>04</span><strong>Dlouhá výdrž</strong><small>Správná péče pro dlouhodobě krásné nehty.</small></div></section>
<section className="lux-content"><div className="lux-services"><p className="lux-kicker">Naše služby</p><h2>Elegantní nehty bez kompromisů.</h2><div className="lux-service-list">{services.map(([title,text],i)=><article key={title}><span>{String(i+1).padStart(2,"0")}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div><div className="info-note"><strong>Profesionální materiály</strong><p>Studio pracuje s gely MK PROFI NAILS, AGLIA a EBD. Vzhledem k zájmu o služby doporučujeme objednání s předstihem.</p></div></div>
<aside className="lux-sidebar" id="objednani"><p className="lux-kicker">Náš tým</p><article className="person-card"><div className="person-monogram">AS</div><div><h3>Alena Strejcová</h3><p>Nehtová designérka</p><a href="tel:+420724247446">+420 724 247 446</a><small>IČO 73673927</small></div></article><article className="person-card"><div className="person-monogram">VH</div><div><h3>Vladimíra Hrdinová</h3><p>Nehtová designérka</p><a href="tel:+420606292826">+420 606 292 826</a><small>IČO 76150666</small></div></article><div className="hours-card"><span>Provozní doba</span><p><strong>Po–Pá</strong> dle objednávek</p><p>Konkrétní termín si domluvte přímo s vybranou designérkou.</p></div></aside></section>
<section className="lux-cta"><div><p className="lux-kicker light">Krása v detailu</p><h2>Upravené ruce.<br/>Pocit, který vydrží.</h2></div><div className="lux-actions"><a className="lux-btn primary" href="tel:+420724247446">Objednat u Aleny</a><a className="lux-btn outline-light" href="tel:+420606292826">Objednat u Vladimíry</a></div></section></main>}
